# Generated by Django 3.2.6 on 2021-08-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='las_donated_date',
            new_name='last_donated_date',
        ),
    ]
