# Generated by Django 3.2.6 on 2021-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('seller_name', models.CharField(max_length=50)),
                ('manufacture_name', models.CharField(max_length=50)),
                ('manufactured_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
