# Generated by Django 3.2.6 on 2021-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_desc', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
