# Generated by Django 3.2.6 on 2021-08-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Website',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Phone_no',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='con_password',
            new_name='website',
        ),
    ]
