# Generated by Django 3.2.6 on 2021-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210820_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_no',
            field=models.BigIntegerField(max_length=40),
        ),
    ]
